export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  CONSEILLER = 'ROLE_CONSEILLER',
  NORMAL_USER = 'ROLE_NORMAL_USER',
  PROFESSIONAL_USER = 'ROLE_PROFESSIONAL_USER',
  STUDENT_USER = 'ROLE_STUDENT_USER',
}
